Progress on validation
AECgeeks/ifc-pipeline-validation pull request #1
Opened 2022-01-22 16:34 UTC by johltn

2022-01-25 12:52 UTC, aothms requested changes

2022-01-25 12:52 UTC, aothms commented on application/checks/check_bsdd.py
> +simple_type_python_mapping = {
This changed in 0.7 https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/ifcopenshell-python/ifcopenshell/validate.py

Better `import simple_type_python_mapping from ifcopenshell.validate`.

2022-01-25 12:52 UTC, aothms commented on application/checks/check_bsdd.py
> +    return classification_props['propertySet'], classification_props['name'], classification_props['dataType'], classification_props['predefinedValue']
This is `operator.itemgetter`

~~~
>>> import operator
>>> d = {'a':1, 'b': 2, 'c': 3}
>>> pack_classification = operator.itemgetter('a', 'b')
>>> pack_classification(d)
(1, 2)
~~~

2022-01-25 12:52 UTC, aothms commented on application/checks/check_bsdd.py
> +    url = "https://bs-dd-api-prototype.azurewebsites.net/api/Domain/v2"
Make relative to `base_url` on L18. Preferably using f-strings.

2022-01-25 12:52 UTC, aothms commented on application/checks/check_bsdd.py
> +    return json.loads(requests.get(base_url + "SearchListOpen/v2/", params={'DomainNamespaceUri': domain_uri}).text)
`json.loads(resp.text)` -> `resp.json()`

2022-01-25 12:52 UTC, aothms commented on application/checks/check_bsdd.py
> +    for domain in get_domains():
It appears this function is called frequently?

`get_domains()` does a network request. That's slow on the client and expensive for the server.

Either make sure the network request functions are called once by storing them in a variable after defining. Like what you do in another file `domains = get_domains()`

Or simply wrap `get_domains()` with the `@functools.cache` decorator.

2022-01-25 12:52 UTC, aothms commented on application/checks/check_bsdd.py
> +    return json.loads(r.text)
Same here `r.json()`

2022-01-25 12:52 UTC, aothms commented on application/checks/check_bsdd.py
> +            list_of_classifications = json.loads(requests.get(base_url + "SearchListOpen/v2/", params=params).text)
Again make sure this is cached.

Just separate function taking params and functools.cache is smart enough to handle it.

2022-01-25 12:52 UTC, aothms commented on application/checks/check_bsdd.py
> +                    # example_classification = [0]
remove comment

2022-01-25 12:52 UTC, aothms commented on application/checks/check_bsdd.py
> +                    return 'No classification matched with the reference code provided.'
We shouldn't return the readable output here, but rather some sort of error code/class. Flask-Babel would be overkill for now, but at least we should have the possibility in the template later to give this another class for or icon or sth.

2022-01-25 12:52 UTC, aothms commented on application/checks/check_bsdd.py
> +    base_url = "https://bs-dd-api-prototype.azurewebsites.net/api/"
base_url not used, define url relative to base_url above

2022-01-25 12:52 UTC, aothms commented on application/checks/check_bsdd.py
> +    base_url = "https://bs-dd-api-prototype.azurewebsites.net/api/"
also r.json() and caching :)

2022-01-25 12:52 UTC, aothms commented on application/checks/check_bsdd.py
> +def control_values(requirements, data):
not used

2022-01-25 12:52 UTC, aothms commented on application/checks/check_bsdd.py
> +    # import pdb; pdb.set_trace()
comments to be removed I suppose

2022-01-25 12:52 UTC, aothms commented on application/checks/check_bsdd_v2.py
> +        rnd_array = np.random.multinomial(100, np.ones(n)/n, size=1)[0]
what's this?

2022-01-25 12:52 UTC, aothms commented on application/checks/check_bsdd_v2.py
> +            sys.stdout.write(rnd_array[idx] * ".")
this throws an exception if idx >= 100

2022-01-25 12:52 UTC, aothms commented on application/checks/check_bsdd_v2.py
> +    if n:
I don't think `if n` is necessary here? Why not just immediately loop over the RelAssocs?

2022-01-25 12:52 UTC, aothms commented on application/checks/check_bsdd_v2.py
> +                    session = database.Session()
I don't think we should create this many sessions

2022-01-25 12:52 UTC, aothms commented on application/checks/check_bsdd_v2.py
> +                    if has_specifications(json.loads(bsdd_response.text)):
bsdd_response.json()  and only call once and store in a dict. It's really a bit lazy and expense to keep doing json parsing.

2022-01-25 12:52 UTC, aothms commented on application/checks/check_bsdd_v2.py
> +                bsdd_result = {"task_id":0,
This looks to me like a good use for a `@dataclass`

2022-01-25 12:52 UTC, aothms commented on application/checks/check_bsdd_v2.py
> +                    if has_specifications(json.loads(bsdd_response.text)):
That way you don't have to keep doing all this string indexing below. Nicer to look at and some type safety for free.

2022-01-25 12:52 UTC, aothms commented on application/checks/check_bsdd_v2.py
> +                            bsdd_result["bsdd_classification_uri"] = constraint_content["namespaceUri"]
I'm a bit worried about all these dict accesses. If there is a missing key we get a KeyError and the entire function halts.

I think we should catch exceptions more granularly and handle them gracefully.

2022-01-25 12:52 UTC, aothms commented on application/checks/check_bsdd_v2.py
> +                            pass
`pass` not necessary here

again, not that many sessions necessary.

2022-01-25 12:52 UTC, aothms commented on application/checks/check_bsdd_v2.py
> +                                    setattr(db_bsdd_result, key, value)
or instead of using a dataclass, why not create a bsdd_result from the beginning instead of this dict?

2022-01-25 12:52 UTC, aothms commented on application/checks/check_bsdd_v2.py
> +                        if USE_DB:
eliminate this code duplication, also below

2022-01-25 12:52 UTC, aothms commented on application/checks/check_syntax.py
> +from lark import Lark, Transformer
Is this file still necessary with the submodule?

2022-01-25 12:52 UTC, aothms commented on application/checks/ids.py
> +import operator
Use ids.py directly contained in ifcopenshell

2022-01-25 12:52 UTC, aothms commented on application/checks/ids.xsd
> +<!-- edited with XMLSpy v2021 (x64) (http://www.altova.com) by Leon van Berlo (Overleaf Investments B.V.) -->
same, shouldn't be in this repo

2022-01-25 12:52 UTC, aothms commented on application/checks/info.py
> +from sqlalchemy import create_engine
why all these imports?

2022-01-25 12:52 UTC, aothms commented on application/checks/info.py
> +    detected_mvd = detected_mvd[1:]
`[1:-1]`

2022-01-25 12:52 UTC, aothms commented on application/checks/info.py
> +    'num_geom':len(ifc_file.by_type("IfcShapeRepresentation")),
In this case we really miss the number of elements? Why is that not included?

Like len(by_type(IfcElement)) or IfcBuildingElement

2022-01-25 12:52 UTC, aothms commented on application/checks/info.py
> +model = session.query(database.model).filter(database.model.code == ifc_fn[:-4]).all()[0]
Same here, it's a bit unnecessary to first create a dict and then copy everything over.

2022-01-25 12:52 UTC, aothms commented on application/checks/mvd_tree.py
> +import requests
Is this necessary?

2022-01-25 12:52 UTC, aothms commented on application/checks/step/parse_file.py
> +from lark import Lark, Transformer
Part of submodule?

2022-01-25 12:52 UTC, aothms commented on application/checks/validate.py
> +from __future__ import print_function
No need to be part of this repo. Already part of ifcopenshell

2022-01-25 12:52 UTC, aothms commented on application/database.py
> +from sqlalchemy.pool import StaticPool
Connection pooling might be a good idea. Why StaticPool? Also, is it actually used?

2022-01-25 12:52 UTC, aothms commented on application/database.py
> +DEVELOPMENT = 1
Remove hardcoded settings

2022-01-25 12:52 UTC, aothms commented on application/database.py
> +    engine = create_engine('sqlite:///'+file_path, connect_args={'check_same_thread': False})
I would use an f-string for this

2022-01-25 12:52 UTC, aothms commented on application/database.py
> +        for attribute in inspect(self).attrs.keys():
Maybe add a comment here what's happening?

2022-01-25 12:52 UTC, aothms commented on application/database.py
> +                d[attribute] = []
This appears to be making a copy of the list in a manual fashion? Why?

2022-01-25 12:52 UTC, aothms commented on application/database.py
> +    license = Column(String,default="private")
Should be an enum?

2022-01-25 12:52 UTC, aothms commented on application/database.py
> +    hours = Column(String)
Should be integers?

2022-01-25 12:52 UTC, aothms commented on application/database.py
> +    status_syntax = Column(String, default='n')
Should be a boolean? Or enum?

2022-01-25 12:52 UTC, aothms commented on application/database.py
> +    #model_id = Column(Integer, ForeignKey('models.id'))
Remove comments if no longer necessary. We have version control.

2022-01-25 12:52 UTC, aothms commented on application/main.py
> +from werkzeug import datastructures
Review unused imports please

2022-01-25 12:52 UTC, aothms commented on application/main.py
> +VALIDATION = 1
make configurable, but can wait probably when we have the blueprints and all

2022-01-25 12:52 UTC, aothms commented on application/main.py
> +    authorization_base_url = 'https://buildingsmartservices.b2clogin.com/buildingsmartservices.onmicrosoft.com/b2c_1a_signupsignin_c/oauth2/v2.0/authorize'
I'd make these configurable as well, but can wait for now

2022-01-25 12:52 UTC, aothms commented on application/main.py
> +        return redirect(url_for('login'))
I don't think this a very nice approach. Not every page view has to go through the entire oauth cycle. We should find a way to only do that when necessary. The tokens have a lifetime. Probably oauthlib has a convenient way to check that.

2022-01-25 12:52 UTC, aothms commented on application/main.py
> +    discovery_response = requests.get(BS_DISCOVERY_URL).json()
Hooray `resp.json()` ;)

2022-01-25 12:52 UTC, aothms commented on application/main.py
> +        db_session.close()
You're not closing the session when the `if` block isn't applicable. That could be quite serious actually.

2022-01-25 12:52 UTC, aothms commented on application/main.py
> +        db_session.close()
... It's better to use a context manager.

~~~
with Session(engine) as session:
   ...
~~~

Then the syntax guarantees a proper lifetime

2022-01-25 12:52 UTC, aothms commented on application/main.py
> +        session = database.Session()
Also here keep an eye on the amount of sessions

2022-01-25 12:52 UTC, aothms commented on application/main.py
> +    extensions = set()
Appears unused

2022-01-25 12:52 UTC, aothms commented on application/main.py
> +    user_id = request.form.to_dict()["user"]
This appears not ok. We should never trust data we get from the client. User id should come from the session state, not a form field that a user can edit.

2022-01-25 12:52 UTC, aothms commented on application/main.py
> +    val_config = request.form.to_dict()
Same here, this I find too risky. We don't properly validate the content of this form. Who knows what kind of malicious content we allow into the system like this.

2022-01-25 12:52 UTC, aothms commented on application/main.py
> +@application.route('/dashboard/<user_id>', methods=['GET'])
This looks bad. If a user knows another persons user_id, he can just construct a URL to read another users dashboard. Again, get user_id from the session state. Never trust user input. A URL is also user input.

2022-01-25 12:52 UTC, aothms commented on application/main.py
> +    saved_models.sort(key=lambda m: m.date)
Small thing, but instead of [::-1] the line below, just add `reverse=True` to the `sort()` function.

2022-01-25 12:52 UTC, aothms commented on application/main.py
> +        session = database.Session()
We should check there that an id is actually owned by the current user (even if leaking progress is not very vital).

2022-01-25 12:52 UTC, aothms commented on application/main.py
> +@application.route('/update_info/<ids>/<number>/<user_id>', methods=['POST'])
Again here, get user_id from session and check that that user has the right to write to these fields

2022-01-25 12:52 UTC, aothms commented on application/main.py
> +    decoded_data = ast.literal_eval(data.decode("utf-8"))
literal_eval() is generally pretty safe, but I still wouldn't apply it to user data just like this. json is probably a bit safer (and more logical considering the data comes from javascript?)

Regardless I would really check that the data received is of the expected type. Just a single string probably.

2022-01-25 12:52 UTC, aothms commented on application/main.py
> +        models = session.query(database.model).all()
This seams very odd. Are you that sure of the order and content of database.model.allI()? What if in the mean time other users are adding models?

Also it's really wasteful to get all the models from the database just for this. What if there are millions of models by now?

2022-01-25 12:52 UTC, aothms commented on application/main.py
> +@application.route('/update_info/<code>', methods=['POST'])
Again check that this function is actually safe considering malicious inputs.

2022-01-25 12:52 UTC, aothms commented on application/main.py
> +@application.route('/update_info_saved/<number>/<user_id>', methods=['POST'])
I have the feeling I have seen several of these kind of functions now. Are they all necessary?

2022-01-25 12:52 UTC, aothms commented on application/main.py
> +@application.route('/reslogs/<i>/<ids>')
Again, validate whether current user has access

2022-01-25 12:52 UTC, aothms commented on application/main.py
> +def view_report2(user_id, id):
Note that checking whether a user has access to a given model can also be put under a python decorator. But user id should never be part of the URL.

2022-01-25 12:52 UTC, aothms commented on application/static/new_report.css
> +/****** reset ******/
This seems very similar to index.css. Please eliminate the need for both

2022-01-25 12:52 UTC, aothms commented on application/static/normalize.css
> +/*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */
If we have normalize.css do we still need the reset in the other css?

2022-01-25 12:52 UTC, aothms commented on application/static/process.js
> +        console.log(r);
We should probably notify the user in case this fails (network issues are always possible

2022-01-25 12:52 UTC, aothms commented on application/static/process.js
> +        var syntaxImg = document.createElement("img");
I don't really understand what this does, but this should be a loop over the 5 different image kinds.

e.g

~~~
['syntaxlog', 'mvdlog', ...].forEach((x, i) => {
  let img = createElement
  img.src
  cell[i].append
});
~~~

2022-01-25 12:52 UTC, aothms commented on application/static/process.js
> +    rows[row_index].cells[7].style.color = "#0070C0";
Please separate out the css, by using appropriate classes.

2022-01-25 12:52 UTC, aothms commented on application/static/process.js
> +    rows[row_index].cells[7].id = "report"
Not sure what's happening here, but id should proabbly be unique

2022-01-25 12:52 UTC, aothms commented on application/static/process.js
> +    a.href = "/download/" + savedModels[i].id.toString();
You can use JS equivalent of f-string by using `/download/${savedModels[i].id}`.

Never needed to call toString() in these kind of cases in JS. (for better or worse, weakly typed language).

Please read up on relative URLs. You don't need to look at the location like that. You can probably just have a URL /download like that and if it starts with / it'll be relative to the domain.

2022-01-25 12:52 UTC, aothms commented on application/static/process.js
> +    rows[row_index].cells[10].style.color = "rgb(224, 101, 101)";
Again please separate out all css here.

You can use a css selector such as `nth-child()`

2022-01-25 12:52 UTC, aothms commented on application/templates/dashboard.html
> +        var toColumnUncomplete = {
I think these should better be in the JS file.

2022-01-25 12:52 UTC, aothms commented on application/static/process.js
> +for (var i = 0; i < savedModels.length; i++) {
I'd really prefer, 

~~~
savedModels.forEach((model, i) => {

});
~~~

The constant repetition of `savedModels[i]` is a bit hard on the eyes and a typo is easily made.

2022-01-25 12:52 UTC, aothms commented on application/static/process.js
> +    licenseSelect.id = "license_" + savedModels[i].code;
create some helper functions for the input creation to remove the duplicated lines and to break up this very long function a bit.

2022-01-25 12:52 UTC, aothms commented on application/static/process.js
> +            var img = document.createElement("IMG");
This should also be CSS. Either a background image or `:before { content }`. Just assign a class to the cell in JS. And let CSS handle the presentation.

2022-01-25 12:52 UTC, aothms commented on application/static/process.js
> +            var img = document.createElement("IMG");
Same for most ofthe other things such as filetype and all. It's also more efficient. Keeps the dom light. Saves a lot of JS code and results in more maintainable code.

2022-01-25 12:52 UTC, aothms commented on application/static/process.js
> +        var url = "/report2/" + userId + "/" + savedModels[i].code;
Same here absolute URL should be sufficient. No neadto mess with window.locatino

2022-01-25 12:52 UTC, aothms commented on application/static/report.js
> +// var bsdd_validation_task = {{ bsdd_validation_task| tojson}};
What does this file do?

2022-01-25 12:52 UTC, aothms commented on application/static/report_consistency.css
> +/****** reset ******/
Needed?

2022-01-25 12:52 UTC, aothms commented on application/templates/report_v2.html
> +<!DOCTYPE html>
Let's get to one report template before merging this PR

2022-01-25 12:52 UTC, aothms commented on application/utils.py
> +def unconcatenate_ids(id):
Seems like this could be a single comprehension

~~~
>>> s = "1234abcd1234"
>>> [s[i:i+4] for i in range(0, len(s), 4)]
['1234', 'abcd', '1234']
~~~

2022-01-25 12:52 UTC, aothms commented on application/wsgi.py
> +    application.run(debug=1)
Quite dangerous

2022-01-26 13:35 UTC, johltn commented on application/static/report.js
> +// var bsdd_validation_task = {{ bsdd_validation_task| tojson}};
removed in 0e71d5b

2022-01-26 13:36 UTC, johltn commented on application/checks/ids.xsd
> +<!-- edited with XMLSpy v2021 (x64) (http://www.altova.com) by Leon van Berlo (Overleaf Investments B.V.) -->
removed in 0e71d5b

2022-01-26 13:36 UTC, johltn commented on application/checks/ids.py
> +import operator
removed in 0e71d5b

2022-01-26 13:36 UTC, johltn commented on application/checks/check_syntax.py
> +from lark import Lark, Transformer
removed in 0e71d5b

2022-02-15 13:13 UTC, merged

2022-02-15 13:13 UTC, aothms commented
🥳 awesome!